name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Instalar dependencias API
      working-directory: api
      run: pip install -r requirements.txt

    - name: Entrenar modelo y generar model.pkl
      working-directory: api
      run: python train_model.py

    - name: Verificar que model.pkl fue generado
      run: |
        echo "Buscando model.pkl generado..."
        find . -name "model.pkl"
        echo "Contenido de api/app/:"
        ls -lh api/app/

    - name: Login en DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Construir imagen API con tag único
      working-directory: api
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/api:${{ env.IMAGE_TAG }} .

    - name: Subir imagen API
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/api:${{ env.IMAGE_TAG }}

    - name: Actualizar manifiesto con nuevo tag
      run: |
        sed -i "s|image: .*/api:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/api:${{ env.IMAGE_TAG }}|" manifests/api-deployment.yaml

    - name: Commit y push de manifiesto actualizado
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config user.name "ci-bot"
        git config user.email "ci@example.com"
        git add manifests/api-deployment.yaml
        git commit -m "Actualizar imagen API a ${{ env.IMAGE_TAG }}" || echo "No hay cambios que commitear"
        git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
        echo "Verificando el remote:"
        git remote -v
        git push origin HEAD:main

    - name: Construir imagen LoadTester
      working-directory: loadtester
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/loadtester:latest .

    - name: Subir imagen LoadTester
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/loadtester:latest

