name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Instalar dependencias API
      run: |
        cd api
        pip install -r requirements.txt

    - name: Entrenar modelo y generar model.pkl
      run: |
        cd api
        python train_model.py

    - name: Login en DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Construir imagen API
      run: |
        cd api
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/api:latest .

    - name: Subir imagen API
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/api:latest

    - name: Construir imagen LoadTester
      run: |
        cd loadtester
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/loadtester:latest .

    - name: Subir imagen LoadTester
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/loadtester:latest
